# Generated by Django 4.0.10 on 2023-08-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='depart_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='return_time',
        ),
    ]
